### ISSUE TITLE
How to custom size image full width and height inside CounterFab

### ISSUE THREAD

**Issue by linhnv-org** [andremion/CounterFab#5]
<com.andremion.counterfab.CounterFab
                android:id="@+id/image_view_cart"
                android:layout_width="32dp"
                android:layout_height="32dp"
                android:src="@drawable/shoppingcart"
                android:layout_alignParentRight="true"
                android:layout_marginRight="@dimen/margin_8dp"
                android:layout_centerVertical="true"
                app:backgroundTint="@null"
                android:background="@null"
                android:scaleType="centerCrop"/>

**Comment by linhnv-org** [comment]
<img width="238" alt="nh ch p man hinh 2017-07-14 luc 23 11 08" src="https://user-images.githubusercontent.com/21221988/28220508-ec9aed0e-68e9-11e7-8115-a28eb93ae541.png">

**Comment by andremion** [comment]
The CounterFab flows the same rule of FloatingActionButton because it is a FAB.
So you can set the size using the xml attribute [app:fabSize](https://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html#attr_android.support.design:fabSize) or the method [setSize](https://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html#setSize(int))
